### ISSUE TITLE
HTTP Single State Test

### ISSUE THREAD

**Issue by dm03514** [dm03514/func-y-test-engine#7]
```
--- 
events: 
  google_request: 
    event_fulfillment_strategy:
       type: poll
       frequency_ms: 200
    transition_condition: 
      type: HTTP
      status_code: 200
    initiator:
      method: GET
      type: HTTP
      url: "http://google.com"
max_timeout: 240000
name: single_http_request_test
start_state: first
version: "1"
```
